---
- name: Create srv directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - "{{ openkat_service_root }}/"
    - "{{ openkat_service_root }}/octopoesapiworker/"

- name: Create octopoes compose file
  ansible.builtin.template:
    src: "octopoes_api_worker-docker-compose.yml.j2"
    dest: "{{ openkat_service_root }}/octopoesapiworker/docker-compose.yml"
    owner: root
    group: root
    mode: '0640'
  notify: Restart openkat_octopoesapiworker service

- name: Create systemd Unit file for octopoes service
  ansible.builtin.template:
    src: "octopoes_api_worker.service.j2"
    dest: /etc/systemd/system/openkat_octopoesapiworker.service
    mode: '0644'
  notify:
    - Reload systemd
    - Restart openkat_octopoesapiworker service

- name: Enable openkat_octopoesapiworker service
  ansible.builtin.systemd:
    name: openkat_octopoesapiworker.service
    enabled: true
    daemon_reload: true # In case the service file was changed
    state: started
    no_block: true

- name: Wait until octopoesapiworker service is active (might take a few tries as it needs to pull the docker image on first run)
  ansible.builtin.systemd:
    name: openkat_octopoesapiworker.service
  register: svc_state
  retries: 25
  delay: 10
  until: svc_state.status.ActiveState == 'active'
  changed_when: false
  when: not ansible_check_mode
