---
- name: "Create or read password files"
  persist_password:
    path: "/etc/openkat/{{ item }}/{{ item }}_password"
    variable: "{{ item | upper }}_PASSWORD"
    fact_name: "openkat_{{ item }}_password"
    rotatedays: "{{ openkat_persistent_password_rotate_days }}"
    owner: root
    group: root
    mode: '0600'
  with_items:
    - postgres
    - rocky
    - katalogus
    - bytes
    - mula

# do not rotate the rabbitmq password
- name: "Create or read password files"
  persist_password:
    path: "/etc/openkat/rabbitmq/rabbitmq_password"
    variable: "RABBITMQ_PASSWORD"
    fact_name: "openkat_rabbitmq_password"
    owner: root
    group: root
    mode: '0600'

# put it in the same directory as the bytes password
- name: "Create or read bytes secret"
  persist_password:
    path: "/etc/openkat/bytes/bytes_secret"
    variable: "OPENKAT_BYTES_SECRET"
    fact_name: "openkat_bytes_secret"
    rotatedays: "{{ openkat_persistent_password_rotate_days }}"
    owner: root
    group: root
    mode: '0600'

# put it in the same directory as the rocky password
- name: "Create or read rocky secret"
  persist_password:
    path: "/etc/openkat/rocky/rocky_secret"
    variable: "OPENKAT_ROCKY_SECRET"
    fact_name: "openkat_rocky_secret"
    rotatedays: "{{ openkat_persistent_password_rotate_days }}"
    owner: root
    group: root
    mode: '0600'

# put it in the same directory as the rocky password
# do not rotate this password, as it is used for the Rocky superuser and rotating it would make it impossible to log in to Rocky after a rotation
- name: "Create or read rocky superuser password"
  persist_password:
    path: "/etc/openkat/rocky/rocky_superuser_password"
    variable: "OPENKAT_ROCKY_SUPERUSER_PASSWORD"
    fact_name: "openkat_rocky_superuser_password"
    owner: root
    group: root
    mode: '0600'

# not really a password, but we want to persist it in a file and this is the logical place to put it
- name: Create superuser email file
  ansible.builtin.template:
    src: superuser_email.j2
    dest: /etc/openkat/rocky/rocky_superuser_email
    owner: root
    group: root
    mode: '0600'
  when: openkat_superuser_email is defined
