---
- name: Set Docker Binary Path
  ansible.builtin.command: which docker
  register: docker_binary_path
  changed_when: false
  failed_when: docker_binary_path.rc != 0
  when: not ansible_check_mode

- name: Set Docker Binary Variable
  ansible.builtin.set_fact:
    docker_binary: "{{ docker_binary_path.stdout | default('/usr/bin/docker') }}"

# check if the lxd user exists and if so, set a variable to use the lxd version of docker
- name: Check if lxd user exists
  ansible.builtin.getent:
    database: passwd
    key: lxd
  register: lxd_user_check
  changed_when: false
  failed_when: false
  when: not ansible_check_mode

- name: Create dummy output in check mode for lxd user check
  ansible.builtin.set_fact:
    lxd_user_check: {"ansible_facts": {"getent_passwd": {}}}
  when: ansible_check_mode

# when the getent check succeeds, the lxd_user_check variable will have ansible facts key, but when it fails
# it will have a msg key with the error message, so we can check for the presence of the msg key to determine if the lxd user exists

- name: Set lxd user to lxd
  ansible.builtin.set_fact:
    lxd_user: lxd
  when:
    - "'msg' not in lxd_user_check"

- name: Set lxd user to root since lxd user does not exist
  ansible.builtin.set_fact:
    lxd_user: root
  when:
    - "'msg' in lxd_user_check"

# do the same for the docker group
- name: Check if docker group exists
  ansible.builtin.getent:
    database: group
    key: docker
  register: docker_group_check
  changed_when: false
  failed_when: false
  when: not ansible_check_mode

- name: Create dummy output in check mode for docker group check
  ansible.builtin.set_fact:
    docker_group_check: {"ansible_facts": {"getent_group": {}}}
  when: ansible_check_mode

- name: Set docker group to docker
  ansible.builtin.set_fact:
    docker_group: docker
  when:
    - "'msg' not in docker_group_check"

- name: Set docker group to root since docker group does not exist
  ansible.builtin.set_fact:
    docker_group: root
  when:
    - "'msg' in docker_group_check"
