---
- name: Create srv directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - "{{ openkat_service_root }}/"
    - "{{ openkat_service_root }}/traefik/"

- name: Create compose file
  ansible.builtin.template:
    src: traefik_docker-compose.yml.j2
    dest: "{{ openkat_service_root }}/traefik/docker-compose.yml"
    mode: '0640'
  notify: Restart traefik service

- name: Create Traefik dynamic configuration
  ansible.builtin.template:
    src: traefik_dynamic.yml.j2
    dest: "{{ openkat_service_root }}/traefik/dynamic.yml"
    mode: '0640'
  notify: Restart traefik service

- name: Create systemd Unit file for traefik
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    mode: '0644'
  notify:
    - Reload systemd
    - Restart traefik service

- name: Enable traefik service
  ansible.builtin.systemd:
    name: traefik.service
    enabled: true
    daemon_reload: true # In case the service file was changed
    state: started
    no_block: true

- name: Wait until traefik service is active (might take a few tries as it needs to pull the docker image on first run)
  ansible.builtin.systemd:
    name: traefik.service
  register: svc_state
  retries: 25
  delay: 10
  until: svc_state.status.ActiveState == 'active'
  changed_when: false
  when: not ansible_check_mode
