---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements-role.yml
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

driver:
  name: docker

platforms:
  - name: openkat-missing-vars
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
  playbooks:
    converge: converge.yml

verifier:
  name: ansible

scenario:
  name: missing-required-vars
  test_sequence:
    - destroy
    - dependency
    - create
    - converge
    - destroy
