---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Bootstrap fake docker tooling for Molecule
      ansible.builtin.import_tasks: ../shared/fake_docker_setup.yml
  roles:
    - role: openkat