---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements-role.yml
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

driver:
  name: docker

platforms:
  - name: openkat-debian12
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
  inventory:
    host_vars:
      openkat-debian12:
        openkat_superuser_fullname: Molecule Admin
        openkat_superuser_email: admin@molecule.test
        openkat_traefik_letsencrypt_admin_email: letsencrypt@molecule.test
        openkat_backupninja_enabled: false
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - create
    - converge
    - idempotence
    - verify
    - destroy